### ISSUE TITLE
Regalo articolo meno caro se ordine con stesso numero mouse e tastiere

### ISSUE THREAD

**Issue by ranghetto** [ranghetto/MTSS-Assignment-2#7]
Se vengono ordinati lo stesso numero di Mouse e Tastiere viene regalato l’articolo meno caro.

**Comment by FakeDaemon** [comment]
su test apply all discount, viene regalato due volte lo stesso oggetto
(10+ mouse)+(mouse==keyboard)
@ranghetto da discutere, intanto risolvo a modo mio
